### ISSUE TITLE
Password Protected Issue While Extracting/Decompressin iRAP Files

### ISSUE THREAD

**Issue by WEESHEANFOO** [nunofonseca/irap#13]
To whom it may concern,

May I know what is the password required for all these password protected files ? Besides I have also tried the .tar version in Linux environment and there are also errors like “tar: Skipping to next header” and “tar: Error exit delayed from previous errors”. All this occur when I am trying to extract/decompress the downloaded .zip and .tar file.

Yours prompt reply is highly appreciated.
Thank you.

Best regards,
Wee Shean

**Comment by nunofonseca** [comment]
Dear Wee Shean,
Could you please be more specific? Which files are you trying to download? What are the commands that you are running?
Cheers.

**Comment by WEESHEANFOO** [comment]
I have downloaded the iRAP.tar.gz file. But when I try to decompress or extract the file, it will prompt erros like “tar: Skipping to next header” and “tar: Error exit delayed from previous errors”. Even I tried to extract the .zip version using Windows, it will prompt that some files are password protected files.

**Comment by nunofonseca** [comment]
There are no encrypted/password protected files.  Unfortunately  I can't tell you anything more with the information provided.

**Comment by nunofonseca** [comment]
There are no encrypted/password protected files. Unfortunately I can't tell you anything more than this with the information provided.
