### ISSUE TITLE
Error at piano step of irap

### ISSUE THREAD

**Issue by syedarshi** [nunofonseca/irap#15]
Hi,

I'm trying to execute example ecoli data to test irap pipeline but unfortunately getting error at piano step. Also when generating report of the analysis, the de folder in report is empty.

Here is the error msg:

[INFO] Data in ecoli_test/bowtie2/cufflinks2/cuffdiff2/GAvsGB.genes_de.tsv loaded: 2893 entries
[INFO] Loading annotation file ecoli_test/data/empty.gene.annot.tsv...
[INFO] Load annot...
[INFO] Loading annotation file ecoli_test/data/empty.gene.annot.tsv...done.
[ERROR] Empty annotation file ecoli_test/data/empty.gene.annot.tsv
/apps/irap_install2/scripts/../aux/mk/irap_gse.mk:140: recipe for target 'ecoli_test/bowtie2/cufflinks2/cuffdiff2/GAvsGB.genes.gse.piano.fisher.go.tsv' failed
make: *** [ecoli_test/bowtie2/cufflinks2/cuffdiff2/GAvsGB.genes.gse.piano.fisher.go.tsv] Error 1

![conf file](https://cloud.githubusercontent.com/assets/13760174/9217481/b12dfbe0-40e5-11e5-8025-28b9cd2c6a6c.png)

**Comment by nunofonseca** [comment]
Hi,

iRAP, by default, generates an empty  tsv file with the gene annotations (in your example is ecoli_test/data/empty.gene.annot.tsv). For running piano iRAP requires the mapping between genes and GO terms or/and Pathways. For a few species iRAP will be able to generate an annotation file  with the GO terms and Patways if the following line appears in the configuration file
annot_tsv=auto

It is also possible to create the file manually (for instance, using biomart). The file contains the following columns tab-separated (the first column is the gene id as it appears in the GTF file):
ID      Name    locus   source  lname   GO      GOterm  KEGG    biotype

Cheers.
