### ISSUE TITLE
Update instructions 

### ISSUE THREAD

**Issue by dsarov** [nunofonseca/irap#16]
Hi Nuno, 

I noticed a small issue with the update instructions. You may want to include the command "source irap_install/irap_setup.sh" in the instructions for how to update. If someone hasn't run iRAP for a while they may forget to setup their environment before the update, which throws an error.

Thanks,

Derek

**Comment by nunofonseca** [comment]
Hi Derek, 
I changed the wiki to include your suggestion.
Thanks.
