### ISSUE TITLE
Latest docker image is not tagged

### ISSUE THREAD

**Issue by moskalenko** [nunofonseca/irap#17]
Since the latest docker image is not tagged in the repository it appears to be necessary to download all of them to get the most recent one.

E.g.

docker pull docker.io/nunofonseca/irap_ubuntu
Using default tag: latest
Trying to pull repository docker.io/nunofonseca/irap_ubuntu ... 
Pulling repository docker.io/nunofonseca/irap_ubuntu
Tag latest not found in repository docker.io/nunofonseca/irap_ubuntu

**Comment by nunofonseca** [comment]
Thanks for the suggestion. The images with the  latest version of iRAP will be tagged with latest.

The docker pull should now be able to find the image with the latest version.
docker pull docker.io/nunofonseca/irap_ubuntu
Using default tag: latest
latest: Pulling from nunofonseca/irap_ubuntu
96c6a1f3c3b0: Pull complete 
ed40d4bcb313: Pull complete 
b171f9dbc13b: Pull complete 
ccfc4df4fbba: Pull complete 
a3ed95caeb02: Pull complete 
f12c01a556fe: Pull complete 
5f54244b44ef: Pull complete 
ce4eb26e51e1: Pull complete 
c1ebc761016d: Pull complete 
ea68c5916446: Pull complete 
6638057fecf4: Pull complete 
5b53b736955a: Pull complete 
Digest: sha256:e093f3f7efe869669c78f164317563fdf2511473a58cc4ea3fc28030f93e7010
Status: Downloaded newer image for nunofonseca/irap_ubuntu:latest

Cheers
