### ISSUE TITLE
normalization of counts returns an error

### ISSUE THREAD

**Issue by stkachev** [nunofonseca/irap#18]
Hi,

I am trying to mimic the steps of ExpressionAtlas pipeline, of experiment [E-MTAB-2836](https://www.ebi.ac.uk/gxa/experiments/E-MTAB-2836/analysis-methods) . To try it out I came up with the following configuration file:

> name=mytest
> species=homo_sapiens
> reference=Homo_sapiens.GRCh38.dna.primary_assembly.fa
> gtf_file=Homo_sapiens.GRCh38.85.gtf
> mapper=tophat2
> quant_method=htseq2
> quant_norm_tool=irap 
> quant_norm_method=rpkm 
> qual_filtering=on
> max_threads=16
> data_dir=uhlen_data
> N1=ERR315326_1.fastq.gz ERR315326_2.fastq.gz
> N1_rs=50
> N1_qual=33
> N1_ins=350
> N1_sd=60
> se=
> pe=N1

When I try a dry run I get the following output:

> ---
> - IRAP 0.8.1p7
> - Developed by Nuno Fonseca (authorname (at) acm.org)
> - This pipeline is distributed  under the terms of the GNU General Public License 3
>   *
> - Initializing...
> - Trying to load configuration file try_quant_norm.conf...
> - Configuration loaded.
> - 
> - Required Parameters:
> -   name=mytest
> -   data_dir=uhlen_data
> -   species=homo_sapiens
> -   reference=Homo_sapiens.GRCh38.dna.primary_assembly.fa
> -       gtf_file  = Homo_sapiens.GRCh38.85.gtf
> -       gff3_file  = mytest/data/Homo_sapiens.GRCh38.85.gff3
> -       Transcripts = /data/stkachev/rnaseq/uhlen_data/reference/homo_sapiens/Homo_sapiens.GRCh38.dna.primary_assembly.cdna.all.fa
> -   pe=N1
> -   N1_sd=60
> -   N1_ins=350
> -   N1_rs=50
> -   N1_qual=33
> -    groups=  parameter not defined, this should be defined if you intend to generate an HTML report for the inferred gene/level/transcript quantification
> -   technical.replicates=NONE
> - 
> - Optional Parameters:
> -   max_threads=16
> -   tmp_dir=uhlen_data/tmp (temporary directory)
> -   mapper=tophat2
> -   quant_method=htseq2
> -   exon_quant=n
> -   transcript_quant=n
> -   quant_norm_tool=irap 
> -   quant_norm_method=rpkm 
> -   mapper_splicing=yes
> -   de_method=none
> -   de_pvalue_cutoff=0.05
>   **/usr/local/irap/scripts/../aux/mk/irap_jbrowse.mk:221: **\* mixed implicit and normal rules.  Stop.**

Now if I comment out quant_norm_tool and quant_norm_method lines then the pipeline starts doing something. It would be nice however to normalization of counts component... How can I enable it to make it work?

Thanks,
Sasha.

**Comment by nunofonseca** [comment]
Dear Sasha,

 thank you for reporting the issue. Could you let me know the command line that you used to ran iRAP?

You can enable the Expression Atlas SOP by simply adding the following line to your configuration file:
sop=atlas

Cheers

**Comment by stkachev** [comment]
The line is like quite simple:

> irap conf=try_quant_norm.conf -n

If I do dry run with sop=atlas option in the conf file it works. In the output however I am noticing that quant_norm_tool and quant_norm_method options are enabled. I'd be curious to use atlas SOP as a starting point and then tweak it, e.g. use STAR/rsem combination... Would that work though given the above error?

**Comment by nunofonseca** [comment]
Dear Sasha,
Apologies for the long time without a reply.  
iRAP will enforce the options of the SOP that you selected when  you set the sop parameter.  Hence the tweaking allowed by iRAP in this case is very limited.
You  can always copy the parameters defined when you select the Atlas SOP (in  https://github.com/nunofonseca/irap/blob/master/aux/mk/irap_defs.mk - around line 100) to you configuration file, remove the sop parameter, and then you can tweak as you like.
Cheers.

**Comment by stkachev** [comment]
Yep, I ended up doing something similar to that. Only instead of removing sop parameter I created my own sop and within that tweaked in various ways. That time it worked!
