### ISSUE TITLE
No multithread for bowtie2-build

### ISSUE THREAD

**Issue by Niklas123Niklas** [nunofonseca/irap#20]
Hey there,
I noticed bowtie2-build is not using multi threads, even if i use the max_threads option in the configuration file. Is there any workaround or option I can pass to iRAP to enable multi thread for bowtie2-build?

Best regards,
Niklas

**Comment by nunofonseca** [comment]
Hi,

In general you may define the number of threads in the configuration file (max_threads
parameter) - https://github.com/nunofonseca/irap/wiki/8-Configuration-file

However, currently this parameter it is not passed to the bowtie2-build program - I'll enable it.

Cheers

**Comment by Niklas123Niklas** [comment]
Hey,

I tried hisat2 as mapper, and there is the same problem. The -p option is not passed to hisat2.

Best regars

**Comment by nunofonseca** [comment]
Yes, for hisat2-build the -p option was not being enabled - it is now fixed in the devel branch.

Thanks.

**Comment by Niklas123Niklas** [comment]
Thanks! It works.

Is it enough if I change 
`bowtie2_index_params=$(bowtie2_index_options)` to 
`bowtie2_index_params=-p $(max_threads) $(bowtie2_index_options)`?
to get the same result for bowtie2-build?

**Comment by Niklas123Niklas** [comment]
Hey,

I found the parameter for bowtie2-build:

> `--threads <int>` By default bowtie2-build is using only one thread. Increasing the number of threads will speed up the index building considerably in most cases.

Is it enough if I change 
`bowtie2_index_params=$(bowtie2_index_options)` 
to
`bowtie2_index_params=--threads $(max_threads) $(bowtie2_index_options)`
to enable the option for bowtie2-build?

**Comment by nunofonseca** [comment]
Hi, 
yes to both questions.  I'll try to include bowtie2 2.2.7 (or later) version in the next release of iRAP.
Cheers.

**Comment by Niklas123Niklas** [comment]
Hey,
sounds good! Do you have a plan when to release next version of iRAP? 
Cheers,

**Comment by nunofonseca** [comment]
It should happen in February.
Cheers.

**Comment by nunofonseca** [comment]
Hi, 
I just  pushed a (minor) new release of iRAP that includes bowtie 2.2.9 and multi-thread  support for bowtie2-build.   Please let me know if it works for you to close this issue.
Thanks.

**Comment by Niklas123Niklas** [comment]
Hey,
Thanks for the fast response! 

I updated as in the Wiki described, but:
1.     `./scripts/irap_install.sh -a -s .` from Wiki did not work -> `./scripts/irap_install.sh -s . -a` did work.
2.    Then I got an error 
`Makefile:490: recipe for target 'yapi.o' failed
make: *** [yapi.o] Error 1`

I try do a full reinstall and report to you.
The log file: [2301171046.txt](https://github.com/nunofonseca/irap/files/723337/2301171046.txt)

**Comment by nunofonseca** [comment]
Hi,
Thanks for the report. The full update (./scripts/irap_install.sh -s . -a) should be working now (devel branch).
You may quickly update the core iRAP code and bowtie2 by running
./scripts/irap_install.sh -s . -u
./scripts/irap_install.sh -s . -x bowtie2

Cheers.

**Comment by Niklas123Niklas** [comment]
Everything works fine for me atm. Data is analysed without error and I did not see problems regarding multithreading so far. Thank you for the help! 
Cheers

**Comment by nunofonseca** [comment]
Great! Thanks for reporting the issues!
Cheers.
