### ISSUE TITLE
VM errors

### ISSUE THREAD

**Issue by freekert** [nunofonseca/irap#21]
In your VM I do the following steps as per the suggestion when I open a terminal:
(A small example is already provided. To process the experiment just type irap conf=ecoli_ex.conf)

```
[irap@localhost ~]$ irap conf=ecoli_ex.conf
*****************************************************
* IRAP 0.8.0p1
* Developed by Nuno Fonseca (authorname (at) acm.org)
* This pipeline is distributed  under the terms of the GNU General Public License 3
*
* Initializing...
13:04:08 19/01/2017 * ERROR: ecoli_ex.conf not found
/home/irap/irap_install/scripts/irap:309: *** Fatal error.  Stop.
[irap@localhost ~]$
```

Then I get ecoli_ex.conf from here: https://github.com/nunofonseca/irap/blob/master/examples/ecoli_example.sh
and I get the following error:

```
[irap@localhost ~]$ irap conf=ecoli_ex.conf
*****************************************************
* IRAP 0.8.0p1
* Developed by Nuno Fonseca (authorname (at) acm.org)
* This pipeline is distributed  under the terms of the GNU General Public License 3
*
* Initializing...
13:04:08 19/01/2017 * ERROR: ecoli_ex.conf not found
/home/irap/irap_install/scripts/irap:309: *** Fatal error.  Stop.
[irap@localhost ~]$ mv ecoli_ex.conf.bak ecoli_ex.conf
[irap@localhost ~]$ irap conf=ecoli_ex.conf
*****************************************************
* IRAP 0.8.0p1
* Developed by Nuno Fonseca (authorname (at) acm.org)
* This pipeline is distributed  under the terms of the GNU General Public License 3
*
* Initializing...
* Trying to load configuration file ecoli_ex.conf...
* Configuration loaded.
* 
* Required Parameters:
*	name=ecoli_ex
*	data_dir=\/home/irap/irap_install/data
13:08:59 19/01/2017 * ERROR: \/home/irap/irap_install/data not found
/home/irap/irap_install/scripts/irap:362: *** Fatal error.  Stop.
[irap@localhost ~]$
```

Any suggestions? Is the config file I got wrong? Where in the VM can I find it?

Thanx,

Freek.

**Comment by freekert** [comment]
Ah, it is found in source irap_install/irap_setup.sh

Never mind.

**Comment by freekert** [comment]
By the way, your DockerFile fails to build:

$ docker build .
Sending build context to Docker daemon 1.838 GB
Step 1/11 : FROM fedora:20
 ---> ba74bddb630e
Step 2/11 : MAINTAINER Nuno Fonseca email: nuno.fonseca at gmail.com
 ---> Using cache
 ---> fdd9b8a8f762
Step 3/11 : RUN sed -i "s/failovermethod=priority/failovermethod=roundrobin/" /etc/yum.repos.d/fedora.repo  && yum update -y && yum install -y zlib-devel python-devel bzip2-devel python readline-devel libgfortran gcc-gfortran gcc-c++ libX11-devel libXt-devel numpy gd-devel libxml2-devel libxml2 libpng libcurl-devel expat-devel  libpangocairo db-devel java python gcc g++ gfortran curl-config git which make bzip2 bison gettext-devel  unzip make wget sqlite sqlite-devel db4-devel libdb-devel graphviz texlive tar java-devel xorg-x11-server-Xvfb && yum clean all
 ---> Running in 94456ff323c5


 One of the configured repositories failed (Fedora 20 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable fedora

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=fedora.skip_if_unavailable=true

Cannot retrieve metalink for repository: fedora/20/x86_64. Please verify its path and try again
The command '/bin/sh -c sed -i "s/failovermethod=priority/failovermethod=roundrobin/" /etc/yum.repos.d/fedora.repo  && yum update -y && yum install -y zlib-devel python-devel bzip2-devel python readline-devel libgfortran gcc-gfortran gcc-c++ libX11-devel libXt-devel numpy gd-devel libxml2-devel libxml2 libpng libcurl-devel expat-devel  libpangocairo db-devel java python gcc g++ gfortran curl-config git which make bzip2 bison gettext-devel  unzip make wget sqlite sqlite-devel db4-devel libdb-devel graphviz texlive tar java-devel xorg-x11-server-Xvfb && yum clean all' returned a non-zero code: 1

**Comment by freekert** [comment]
My issues remain but just to let you know, I have got the whole thing working now, pulling a docker from docker hub. Feel free to delete my ramblings, my apologies.
What I did was:
`docker run -it nunofonseca/irap_ubuntu /bin/bash`
Thank you for the nice software.

**Comment by nunofonseca** [comment]
Great that is working now. Thanks for letting me know about the fedora 20 docker file problem - it seems that  Fedora no longer supports version 20. There is a new docker file for Fedora 22 in the devel branch. Meanwhile you may find docker files for more recent versions of Fedora in the docker/install_tests folder. The escape character in example has also been fixed. Please reopen the issue of the problem persists.
Cheers.
