### ISSUE TITLE
Problem dry-running the ecoli_ex.conf file

### ISSUE THREAD

**Issue by ikramu** [nunofonseca/irap#22]
Hi,

After installing IRAP from sources, I tried to dry-run the ecoli_ex.conf file (while in irap_install directory) as follows

ikramu:irap_install$ ./scripts/irap conf=ecoli_ex.conf mapper=tophat1 de_method=deseq max_threads=8 -n

but got the following errors.
scripts/irap:1302: /../aux/mk/irap_map.mk: No such file or directory
scripts/irap:1304: /../aux/mk/irap_jbrowse.mk: No such file or directory
scripts/irap:1306: /../aux/mk/irap_report.mk: No such file or directory
scripts/irap:1308: /../aux/mk/irap_citations.mk: No such file or directory
scripts/irap:1310: /../aux/mk/irap_quant.mk: No such file or directory
scripts/irap:1312: /../aux/mk/irap_norm.mk: No such file or directory
scripts/irap:1314: /../aux/mk/irap_de.mk: No such file or directory
scripts/irap:1316: /../aux/mk/irap_gse.mk: No such file or directory
scripts/irap:1319: /../aux/mk/irap_atlas.mk: No such file or directory
scripts/irap:1322: /../aux/mk/irap_fusion.mk: No such file or directory
scripts/irap:1334: warning: undefined variable 'gse_tool'
bash: irap_paths: command not found

Can you please guide if there is any path I forgot to set?

Thanks!
Ikram

**Comment by nunofonseca** [comment]
Hi,
It seems that iRAP environment variables are not defined. Did you skip the [configuration step](https://github.com/nunofonseca/irap/wiki/2---How-to-install-and-update-iRAP#finish-the-configuration)?
Cheers

**Comment by nunofonseca** [comment]
Please reopen the ticket if the problem persists.
Cheers.
