### ISSUE TITLE
IGV_VERSION=2.1.24

### ISSUE THREAD

**Issue by freekvh** [nunofonseca/irap#23]
Dear Mr. Fonseca,

The IGV version included in iRAP is from 2012. This version fails to load some things from the internet. The new version also has some nice improvements.

Best regards,

Freek.

**Comment by nunofonseca** [comment]
Hi,
Indeed the version of IGV is quite old. Once a year I update the version of most of the tools in iRAP - this should happen in the coming months and I'll include IGV in the set of tools to update.

Regards,

Nuno

**Comment by freekvh** [comment]
Ok, great, thank you.

**Comment by nunofonseca** [comment]
The IGV version will be upgraded in the up coming major new release of iRAP (0.9.0) that should happen in June.
