### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Niklas123Niklas** [nunofonseca/irap#24]
Hey Nuno,

i am having Problems with the new version. If I run .conf files that worked in last version, now I get an error:
`[INFO] #Genes: 58051`
`[INFO] #Transcripts: 198002`
`[INFO] #Exons: 1182163`
`Having no space between pattern and following word is deprecated at (eval 1) line 1.`
`Bareword found where operator expected at (eval 1) line 1, near "/home/niklas"`
`	(Missing operator before niklas?)`
`Bareword found where operator expected at (eval 1) line 1, near "87.gtf"`
`	(Missing operator before gtf?)`
`syntax error at (eval 1) line 1, near "/home/niklas"`
`/home/niklas/irap_install/scripts/irap:1616: recipe for target '/home/niklas/irap_install/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf.lengths.Rdata' failed`
`make: *** [/home/niklas/irap_install/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf.lengths.Rdata] Error 255`

Line 1616 in scripts/irap  is
`irap_gtf2featlength --gtf $< -o $@.tmp --cores $(max_threads) && mv $@.tmp.Rdata $@ && rename "$(gtf_file_abspath).lengths.Rdata.tmp" "$(gtf_file_abspath)" $@.tmp.*`

Is this a bug or did I do something wrong?

**Comment by nunofonseca** [comment]
Hi,
Can you post the full ouput of running irap (and add --trace to the list of command line options)?
Thanks,
Nuno

**Comment by Niklas123Niklas** [comment]
Hey,
I will rerun with:
  `irap --trace conf=RNA_1_4Core.conf`

Is this correct?

**Comment by nunofonseca** [comment]
No, there is no log file - everything is printed to stdout (but it may be redirected to a file).
Could you then run 

irap --trace conf=RNA_1_4Core.conf &> logfile

and post the logfile?

**Comment by Niklas123Niklas** [comment]
Hey,

I did it now, but with the --trace option, I got a different error message. I start a run without trace and see what happens then.

But here is the log.
[log.txt](https://github.com/nunofonseca/irap/files/954886/log.txt)

**Comment by nunofonseca** [comment]
Thanks, the log file is quite useful as is. I suspect that you are running iRAP in a debian based distribution. Is that true?

**Comment by Niklas123Niklas** [comment]
Hey,
thats good to hear. I use Ubuntu 12.04.

**Comment by nunofonseca** [comment]
It seems that the rename command in Debian is different from the other distros and that is causing the error. I'll try to fix it and release a patch in the coming days.

**Comment by nunofonseca** [comment]
Hi,
The issue should be fixed in the new release. Please reopen the ticket if the problem persists.
Cheers.
