### ISSUE TITLE
Unknown regexp modifier "/t" at (eval 1) line 1, at end of line

### ISSUE THREAD

**Issue by jodyphelan** [nunofonseca/irap#26]
Hi,

I am getting the following error while running irap:

Time taken:  0.02338505  s
[INFO] Saved length of genes, transcripts and exons to /mnt/storage/jody/RNAseq/analysis/data/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf.lengths.Rdata.tmp.Rdata
[INFO] -->/mnt/storage/jody/RNAseq/analysis/data/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf.lengths.Rdata.tmp.gene_length.tsv

[INFO] -->/mnt/storage/jody/RNAseq/analysis/data/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf.lengths.Rdata.tmp.exon_length.tsv

[INFO] -->/mnt/storage/jody/RNAseq/analysis/data/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf.lengths.Rdata.tmp.trans_length.tsv

[INFO] #Genes: 26247
[INFO] #Transcripts: 28294
[INFO] #Exons: 236018
Unknown regexp modifier "/t" at (eval 1) line 1, at end of line
Unknown regexp modifier "/r" at (eval 1) line 1, at end of line
Unknown regexp modifier "/e" at (eval 1) line 1, at end of line
Bareword "jody" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "RNAseq" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "analysis" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "data" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "reference" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "Ovis_aries" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "Ovis_aries" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "Oar_v3" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "gtf" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "lengths" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "Rdata" not allowed while "strict subs" in use at (eval 1) line 1.
Bareword "tmp" not allowed while "strict subs" in use at (eval 1) line 1.
/mnt/storage/jody/software/irap_install/scripts/irap:1616: recipe for target '/mnt/storage/jody/RNAseq/analysis/data/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf.lengths.Rdata' failed
make: *** [/mnt/storage/jody/RNAseq/analysis/data/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf.lengths.Rdata] Error 255

Not sure if it is anything to do with the input files or the scripts themselves. Any help appreciated!

Jody

**Comment by nunofonseca** [comment]
Hi! 
Thanks for reporting the issue. Two initial questions to try to pinpoint the cause of the problem.
i) what is the version of iRAP that you are using?
ii) What is the Linux distribution and version were you are running iRAP? 
Cheers.

**Comment by jodyphelan** [comment]
I am running Ubuntu 14.04.5 LTS. With iRAP version 0.8.5.
It is the first time I am running it.

Thanks!

**Comment by nunofonseca** [comment]
Thanks.  I think that the issue you reported  has been fixed. Could you please update iRAP to the latest version and try again?
Cheers.

**Comment by jodyphelan** [comment]
I've updated and it is working now. Thanks
