### ISSUE TITLE
make: *** No rule to make target '

### ISSUE THREAD

**Issue by jodyphelan** [nunofonseca/irap#28]
Hi 

I am getting an error:

make: *** No rule to make target 'sheep/data/Ovis_aries.Oar_v3.1.88.chr.gtf.mapTrans2Gene.tsv', needed by 'sheep/star/cufflinks2//pt0a.se.transcripts.riu.cufflinks2.irap.tsv'. Stop.

Is there some additional file I have to include?

Thanks,
Jody

**Comment by nunofonseca** [comment]
Hi! 
Thanks for reporting the issue. Can you please post the full output that you got when you ran iRAP? If you do not have it then you can simply rerun the same command on the same folder - it should fail quickly.
Thanks.

**Comment by jodyphelan** [comment]
Sure, here it is


*****************************************************
* IRAP 0.8.5p1
* Developed by Nuno Fonseca (authorname (at) acm.org)
* This pipeline is distributed  under the terms of the GNU General Public License 3
*
* Initializing...
* Trying to load configuration file sheep.conf...
* Configuration loaded.
* 
* Required Parameters:
*	name=sheep
*	data_dir=poly
*	species=Ovis_aries
*	reference=Ovis_aries.Oar_v3.1.dna.fa
*       gtf_file  = Ovis_aries.Oar_v3.1.88.chr.gtf
*       gff3_file  = sheep/data/Ovis_aries.Oar_v3.1.88.chr.gff3
*       Transcripts = /mnt/storage/jody/RNAseq/analysis/poly/reference/Ovis_aries/Ovis_aries.Oar_v3.1.cdna.all.fa
*	se=pt0a pt0b pt0c pt8a pt8b pt8c
*	pt0a_rs=51
*	pt0b_rs=51
*	pt0c_rs=51
*	pt8a_rs=51
*	pt8b_rs=51
*	pt8c_rs=51
*	pt0a_qual=33
*	pt0b_qual=33
*	pt0c_qual=33
*	pt8a_qual=33
*	pt8b_qual=33
*	pt8c_qual=33
*	contrasts=hour0Vshour8
*      hour0Vshour8=hour0 hour8
*	hour0=pt0a pt0b pt0c
*	hour8=pt8a pt8b pt8c
*	hour0=pt0a pt0b pt0c
*	hour8=pt8a pt8b pt8c
*	groups=hour0 hour8
*	technical.replicates=NONE
* 
* Optional Parameters:
*	max_threads=35
*	tmp_dir=poly/tmp (temporary directory)
*	mapper=star
*	quant_method=cufflinks2
Enabling transcript_quant since  cufflinks2 supports it by default
*	exon_quant=n
*	transcript_quant=y
* Enabling generation of table of FPKMs since cufflinks2 produces F/RPKMs by default
*	quant_norm_tool=cufflinks2
*	quant_norm_method=fpkm
*	mapper_splicing=yes
*	de_method=deseq
*	de_pvalue_cutoff=0.05
*	gse_tool=none
% YAP execution halted
*========================================================
DEBUG
reference_prefix=/mnt/storage/jody/RNAseq/analysis/poly/reference/Ovis_aries/Ovis_aries.Oar_v3.1.dna.fa
gtf_file_abspath=/mnt/storage/jody/RNAseq/analysis/poly/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf
index_files=	/mnt/storage/jody/RNAseq/analysis/poly/reference/Ovis_aries/Ovis_aries.Oar_v3.1.dna.fa.star.index 
files_indexed=/mnt/storage/jody/RNAseq/analysis/poly/reference/Ovis_aries/Ovis_aries.Oar_v3.1.dna.fa /mnt/storage/jody/RNAseq/analysis/poly/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.gtf
feat_mapping_file=/mnt/storage/jody/RNAseq/analysis/poly/reference/Ovis_aries/Ovis_aries.Oar_v3.1.88.chr.mapping.Rdata
19:53:25 04/05/2017 *  [DONE] Initialization
QC disabled
19:53:25 04/05/2017 *  [DONE] Directory structure created
19:53:25 04/05/2017 *  [DONE] Quality filtering
19:53:25 04/05/2017 *  [DONE] Mapping
make: *** No rule to make target 'sheep/data/Ovis_aries.Oar_v3.1.88.chr.gtf.mapTrans2Gene.tsv', needed by 'sheep/star/cufflinks2//pt0a.se.transcripts.riu.cufflinks2.irap.tsv'. Stop.


Thanks,
jody

**Comment by nunofonseca** [comment]
Hi, 
Thanks, I think that I introduced the bug recently - I'll release a fix in the coming days.
Cheers.

**Comment by freekvh** [comment]
Hi,

I just want to chime in, saying I have the same error. I updated my reference genome recently and after removing all comment lines from the GTF file (which lead to an error) and updating the config file, iRAP crashes with the following message:

`[2017-05-10 04:47:17] Beginning TopHat run (v2.1.1)
-----------------------------------------------
[2017-05-10 04:47:17] Checking for Bowtie
                  Bowtie version:        2.2.9.0
[2017-05-10 04:47:17] Checking for Bowtie index files (transcriptome)..
[2017-05-10 04:47:17] Checking for Bowtie index files (genome)..
[2017-05-10 04:47:17] Checking for reference FASTA file
[2017-05-10 04:47:17] Generating SAM header for /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.dna.fa
[2017-05-10 04:48:30] Reading known junctions from GTF file
[2017-05-10 04:48:59] Preparing reads
         left reads: min. length=128, max. length=128, 24917 kept reads (5 discarded)
        right reads: min. length=128, max. length=128, 24916 kept reads (6 discarded)
[2017-05-10 04:49:00] Using pre-built transcriptome data..
[2017-05-10 04:49:07] Mapping left_kept_reads to transcriptome Homo_sapiens.GRCh38.87 with Bowtie2
[2017-05-10 04:49:17] Mapping right_kept_reads to transcriptome Homo_sapiens.GRCh38.87 with Bowtie2
[2017-05-10 04:49:26] Resuming TopHat pipeline with unmapped reads
[2017-05-10 04:49:26] Mapping left_kept_reads.m2g_um to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2
[2017-05-10 04:49:43] Mapping left_kept_reads.m2g_um_seg1 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (1/6)
[2017-05-10 04:49:45] Mapping left_kept_reads.m2g_um_seg2 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (2/6)
[2017-05-10 04:49:47] Mapping left_kept_reads.m2g_um_seg3 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (3/6)
[2017-05-10 04:49:49] Mapping left_kept_reads.m2g_um_seg4 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (4/6)
[2017-05-10 04:49:51] Mapping left_kept_reads.m2g_um_seg5 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (5/6)
[2017-05-10 04:49:54] Mapping left_kept_reads.m2g_um_seg6 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (6/6)
[2017-05-10 04:49:57] Mapping right_kept_reads.m2g_um to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2
[2017-05-10 04:50:07] Mapping right_kept_reads.m2g_um_seg1 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (1/6)
[2017-05-10 04:50:09] Mapping right_kept_reads.m2g_um_seg2 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (2/6)
[2017-05-10 04:50:11] Mapping right_kept_reads.m2g_um_seg3 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (3/6)
[2017-05-10 04:50:13] Mapping right_kept_reads.m2g_um_seg4 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (4/6)
[2017-05-10 04:50:15] Mapping right_kept_reads.m2g_um_seg5 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (5/6)
[2017-05-10 04:50:18] Mapping right_kept_reads.m2g_um_seg6 to genome Homo_sapiens.GRCh38.87.dna.fa with Bowtie2 (6/6)
[2017-05-10 04:50:22] Searching for junctions via segment mapping
[2017-05-10 04:51:38] Retrieving sequences for splices
[2017-05-10 04:52:55] Indexing splices
Building a SMALL index
[2017-05-10 04:53:17] Mapping left_kept_reads.m2g_um_seg1 to genome segment_juncs with Bowtie2 (1/6)
[2017-05-10 04:53:20] Mapping left_kept_reads.m2g_um_seg2 to genome segment_juncs with Bowtie2 (2/6)
[2017-05-10 04:53:23] Mapping left_kept_reads.m2g_um_seg3 to genome segment_juncs with Bowtie2 (3/6)
[2017-05-10 04:53:26] Mapping left_kept_reads.m2g_um_seg4 to genome segment_juncs with Bowtie2 (4/6)
[2017-05-10 04:53:29] Mapping left_kept_reads.m2g_um_seg5 to genome segment_juncs with Bowtie2 (5/6)
[2017-05-10 04:53:32] Mapping left_kept_reads.m2g_um_seg6 to genome segment_juncs with Bowtie2 (6/6)
[2017-05-10 04:53:35] Joining segment hits
[2017-05-10 04:54:52] Mapping right_kept_reads.m2g_um_seg1 to genome segment_juncs with Bowtie2 (1/6)
[2017-05-10 04:54:55] Mapping right_kept_reads.m2g_um_seg2 to genome segment_juncs with Bowtie2 (2/6)
[2017-05-10 04:54:59] Mapping right_kept_reads.m2g_um_seg3 to genome segment_juncs with Bowtie2 (3/6)
[2017-05-10 04:55:02] Mapping right_kept_reads.m2g_um_seg4 to genome segment_juncs with Bowtie2 (4/6)
[2017-05-10 04:55:05] Mapping right_kept_reads.m2g_um_seg5 to genome segment_juncs with Bowtie2 (5/6)
[2017-05-10 04:55:08] Mapping right_kept_reads.m2g_um_seg6 to genome segment_juncs with Bowtie2 (6/6)
[2017-05-10 04:55:11] Joining segment hits
[2017-05-10 04:56:28] Reporting output tracks
-----------------------------------------------
[2017-05-10 04:57:46] A summary of the alignment counts can be found in xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib/align_summary.txt
[2017-05-10 04:57:46] Run complete: 00:10:28 elapsed unaligned MAPQ fixes: 0 unaligned mtid fixes: 9198 unaligned mpos fixes: 0 No reordering of @SQ entries required in BAM file xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib/xxsMCF7_50_S2Lib.tmp.bam
04:57:48 10/05/2017 *  [DONE] Mapping
rm -f xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.byname.tmp.{0,1,2,3,4,5,6,7,8,9}*.bam && samtools sort -n -m 4G -T xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.byname.tmp -o xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.byname.tmp.bam xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.bam && mv xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.byname.tmp.bam xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.byname.bam
mkdir -p xxsMCF7_50_S2/tophat2/htseq2/ &&               samtools view -F 4 xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.byname.bam | htseq-count    -m intersection-nonempty         --stranded=no --idattr gene_id  -q   - /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf  > xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv.tmp && tail -n -5 xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv.tmp > xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv.htseq2.stats && head -n -5 xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv.tmp > xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv.tmp2 && mv xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv.tmp2 xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv && rm -f xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv.tmp
( irap_merge_tsv.sh xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.genes.raw.htseq2.tsv  ) > xxsMCF7_50_S2/tophat2/htseq2/genes.raw.htseq2.tsv.tmp && mv xxsMCF7_50_S2/tophat2/htseq2/genes.raw.htseq2.tsv.tmp xxsMCF7_50_S2/tophat2/htseq2/genes.raw.htseq2.tsv
BASENAME=yes
mkdir -p xxsMCF7_50_S2/tophat2/htseq2/ &&               samtools view -F 4 xxsMCF7_50_S2/tophat2//xxsMCF7_50_S2Lib.pe.hits.byname.bam | htseq-count    -m intersection-nonempty         --stranded=no --idattr transcript_id  -q   - /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf  > xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv.tmp && tail -n -5 xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv.tmp > xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv.htseq2.stats && head -n -5 xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv.tmp > xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv.tmp2 && mv xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv.tmp2 xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv && rm -f xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv.tmp
make: *** No rule to make target 'xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv', needed by 'xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.riu.htseq2.irap.tsv'.  Stop.
`
(I'm testing with truncated fastq files by the way)

Hope this helps in solving this bug.

Highest regards,

Freek.

**Comment by nunofonseca** [comment]
Hi both,

I just release a patched version of iRAP that should fix the issue.  
Please update iRAP (as described in the link below - no need to install everything) and let me know if the issue persists:
https://github.com/nunofonseca/irap/wiki/2---How-to-install-and-update-iRAP#update
Cheers.

**Comment by jodyphelan** [comment]
Thanks I'll give it a try :)

Jody

**Comment by freekvh** [comment]
Hi Nuno,

Thanx for the fix, it solved the problem but introduced another one. I ran iRAP and encountered the problem below. I wonder, is it necessary to re-make all the "helper" files (like Homo_sapiens.GRCh38.87.mapping_exons.tsv, Homo_sapiens.GRCh38.87.mapping.Rdata, etc) by deleting them?

Highest regards,

Freek

<pre>
[08:25 nlv24077@lardos /home/2017-0205_illuminaseq/data/seqData/analyzed/TEMP] irap conf=xxsMCF7_50_S2.conf
*****************************************************
* IRAP 0.8.5p2
* Developed by Nuno Fonseca (authorname (at) acm.org)
* This pipeline is distributed  under the terms of the GNU General Public License 3
*
* Initializing...
* Trying to load configuration file xxsMCF7_50_S2.conf...
* Configuration loaded.
*
* Required Parameters:
*	name=xxsMCF7_50_S2
*	data_dir=/home/genomics_scratch/iraptest/data
*	species=homo_sapiens
*	reference=Homo_sapiens.GRCh38.87.dna.fa
*       gtf_file  = Homo_sapiens.GRCh38.87.gtf
*       gff3_file  = xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gff3
*       Transcripts = /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.cdna.all.fa
*	pe=xxsMCF7_50_S2Lib
*	xxsMCF7_50_S2Lib_sd=60
*	xxsMCF7_50_S2Lib_ins=200
*	xxsMCF7_50_S2Lib_rs=151
*	xxsMCF7_50_S2Lib_qual=33
*	 groups=  parameter not defined, this should be defined if you intend to generate an HTML report for the inferred gene/level/transcript quantification
*	technical.replicates=NONE
*
* Optional Parameters:
*	max_threads=1
*	tmp_dir=/home/genomics_scratch/iraptest/data/tmp (temporary directory)
*	mapper=tophat2
*	quant_method=htseq2
*	exon_quant=y
*	exon_quant_method=dexseq
*	transcript_quant=y
*	quant_norm_tool=irap
*	quant_norm_method=tpm
*	mapper_splicing=yes
*	de_method=none
*	de_pvalue_cutoff=0.05
*	gse_tool=none
% YAP execution halted
*========================================================
DEBUG
reference_prefix=/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.dna.fa
gtf_file_abspath=/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf
index_files=		/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.dna.fa.1.bt2 /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.dna_Homo_sapiens.GRCh38.87_th2_trans
files_indexed=/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.dna.fa /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf
feat_mapping_file=/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.Rdata
08:26:17 12/05/2017 *  [DONE] Initialization
08:26:17 12/05/2017 *  [DONE] Directory structure created genMapTrans2Gene -i /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf -o xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv.tmp -c 1 && mv xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv.tmp xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv
[INFO] Loading /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf
grep: write error
Read 1956156 rows and 9 (of 9) columns from 0.996 GB file in 00:00:26 GTF attributes  gencode [1] 1956156 [INFO] biotype col:gene_biotype Warning message:
In fread(input = f, sep = "\t", header = "auto", check.names = FALSE,  :
  Bumped column 1 to type character on data row 1035926, field contains 'X'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses a sample of 1,000 rows (100 rows at 10 points) so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.
[INFO] GTF file loaded
[1] 149315
09:42:25 12/05/2017 *  [DONE] Quality filtering
09:42:25 12/05/2017 *  [DONE] Mapping
irap_transcript_gene_rel_expr --tsv xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.raw.htseq2.tsv  --map xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv --cores 1  --gene_col 1 --trans_col 2  --out xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.riu.htseq2.irap.tsv.tmp && mv xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.riu.htseq2.irap.tsv.tmp xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.riu.htseq2.irap.tsv	
            trans            gene
1 ENST00000456328 ENSG00000223972
2 ENST00000450305 ENSG00000223972
3 ENST00000488147 ENSG00000227232
4 ENST00000619216 ENSG00000278267
5 ENST00000473358 ENSG00000243485
6 ENST00000469289 ENSG00000243485
[INFO] Data loaded
[1] "ENST00000002501" "ENST00000004982" "ENST00000005284" "ENST00000005340"
[5] "ENST00000006053" "ENST00000006251"
[ERROR] Transcripts not found in the xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv mapping file.
/home/genomics/testsw/irap-0.8.5p2/scripts/../aux/mk/irap_quant.mk:1045: recipe for target 'xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.riu.htseq2.irap.tsv' failed
make: *** [xxsMCF7_50_S2/tophat2/htseq2//xxsMCF7_50_S2Lib.pe.transcripts.riu.htseq2.irap.tsv] Error 2
[09:42 nlv24077@lardos /home/2017-0205_illuminaseq/data/seqData/analyzed/TEMP]
</pre>

**Comment by nunofonseca** [comment]
Hi,
There should not be necessary to delete or regenerate files (but if you wish to regenerate the files you can just add the option -B to the irap command).
Regarding the error, it seems that there is an inconsistency between the gtf file and the file with the transcripts (Homo_sapiens.GRCh38.87.cdna.all.fa) - some transcripts are missing. There are two main possible causes: i) the files you got from Ensembl are inconsistent (unfortunately it would not be the first time); ii)  the file  xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv is corrupted somehow. I'm putting forward the ii) option because  I noticed a strange 'write error' message. If it was indeed an I/O issue  you may confirm it by regenerating only the file  xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv:

rm xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv
irap conf=xxsMCF7_50_S2.conf xxsMCF7_50_S2/data/Homo_sapiens.GRCh38.87.gtf.mapTrans2Gene.tsv

Cheers.

**Comment by freekvh** [comment]
Hi Nuno,

Thank you for your very rapid replies, it is highly appreciated!

The write error was indeed the relevant error, it is followed by
<pre>Read 1956156 rows and 9 (of 9) columns from 0.996 GB file</pre>
But the GTF file is 1.4 GB.

Some further investigation of irap_gtf2mapping (raw strace output below) showed that our command:
<pre>
irap_gtf2mapping --gtf /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf --out /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp
</pre>
writes to /dev/shm. This results in grep: `write error'. In our infrastructure /dev/shm is limited to 1GB, so irap_gtf2mapping fills it up.

We wondered if we can configure the directory in which it writes with an environment variable?

We were able to increase the size of /dev/shm  and now the error is gone and we see:
<pre>Read 2575494 rows and 9 (of 9) columns from 1.312 GB file</pre>

I'm pretty sure this solves the problem (although iRAP is still running, fingers crossed :))

Again my highest regards, enjoy the weekend,

Freek.

=>

Here is the raw strace output for more information:
<pre>
strace -f -e execve -s1024 irap_gtf2mapping --debug --gtf /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf --out /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp3
execve("/home/genomics/testsw/irap-0.8.5p2/scripts/irap_gtf2mapping", ["irap_gtf2mapping", "--debug", "--gtf", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf", "--out", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp3"], [/* 168 vars */]) = 0 execve("/home/genomics/testsw/irap-0.8.5p2/R3/bin/Rscript", ["Rscript", "/home/genomics/testsw/irap-0.8.5p2/scripts/irap_gtf2mapping", "--debug", "--gtf", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf", "--out", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp3"], [/* 168 vars */]) = -1 ENOENT (No such file or directory) execve("/home/genomics/testsw/irap-0.8.5p2/bin/bowtie1/bin/Rscript", ["Rscript", "/home/genomics/testsw/irap-0.8.5p2/scripts/irap_gtf2mapping", "--debug", "--gtf", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf", "--out", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp3"], [/* 168 vars */]) = -1 ENOENT (No such file or directory) execve("/home/genomics/testsw/irap-0.8.5p2/bin/Rscript", ["Rscript", "/home/genomics/testsw/irap-0.8.5p2/scripts/irap_gtf2mapping", "--debug", "--gtf", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf", "--out", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp3"], [/* 168 vars */]) = 0 execve("/home/genomics/testsw/irap-0.8.5p2/lib64/R/bin/R", ["/home/genomics/testsw/irap-0.8.5p2/lib64/R/bin/R", "--slave", "--no-restore", "--file=/home/genomics/testsw/irap-0.8.5p2/scripts/irap_gtf2mapping", "--args", "--debug", "--gtf", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf", "--out", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp3"], [/* 169 vars */]) = 0 Process 39321 attached [pid 39321] execve("/bin/uname", ["uname", "-m"], [/* 167 vars */]) = 0 [pid 39321] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39321, si_status=0, si_utime=0, si_stime=0} --- Process 39322 attached Process 39323 attached Process 39324 attached Process 39325 attached [pid 39324] execve("/bin/sed", ["/bin/sed", "-e", "s/[^=]*=//"], [/* 172 vars */] <unfinished ...> [pid 39323] +++ exited with 0 +++ [pid 39325] execve("/bin/sed", ["/bin/sed", "-e", "s/ /~+~/g"], [/* 172 vars */] <unfinished ...>
[pid 39324] <... execve resumed> )      = 0
[pid 39325] <... execve resumed> )      = 0
[pid 39324] +++ exited with 0 +++
[pid 39325] +++ exited with 0 +++
[pid 39322] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39323, si_status=0, si_utime=0, si_stime=0} --- [pid 39322] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39322, si_status=0, si_utime=0, si_stime=0} --- execve("/home/genomics/testsw/irap-0.8.5p2/lib64/R/bin/exec/R", ["/home/genomics/testsw/irap-0.8.5p2/lib64/R/bin/exec/R", "--slave", "--no-restore", "--file=/home/genomics/testsw/irap-0.8.5p2/scripts/irap_gtf2mapping", "--args", "--debug", "--gtf", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf", "--out", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.mapping.tmp3"], [/* 172 vars */]) = 0 Process 39329 attached [pid 39329] execve("/bin/sh", ["sh", "-c", "grep processor /proc/cpuinfo 2>/dev/null | wc -l"], [/* 189 vars */]) = 0 Process 39330 attached Process 39331 attached [pid 39331] execve("/usr/bin/wc", ["wc", "-l"], [/* 190 vars */]) = 0 [pid 39330] execve("/bin/grep", ["grep", "processor", "/proc/cpuinfo"], [/* 190 vars */]) = 0 [pid 39330] +++ exited with 0 +++ [pid 39331] +++ exited with 0 +++ [pid 39329] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39330, si_status=0, si_utime=0, si_stime=0} --- [pid 39329] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39329, si_status=0, si_utime=0, si_stime=0} --- Process 39332 attached [pid 39332] execve("/bin/sh", ["sh", "-c", "(cat /home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf | grep -v \"^#\") > /dev/shm/file99982aa2b159"], [/* 189 vars */]) = 0 Process 39333 attached Process 39334 attached Process 39335 attached [pid 39334] execve("/bin/cat", ["cat", "/home/genomics_scratch/iraptest/data/reference/homo_sapiens/Homo_sapiens.GRCh38.87.gtf"], [/* 190 vars */]) = 0 [pid 39335] execve("/bin/grep", ["grep", "-v", "^#"], [/* 190 vars */]) = 0
grep: write error
[pid 39335] +++ exited with 2 +++
[pid 39334] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=39334, si_uid=729} --- [pid 39334] +++ killed by SIGPIPE +++ [pid 39333] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39335, si_status=2, si_utime=51, si_stime=178} --- [pid 39333] +++ exited with 2 +++ [pid 39332] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39333, si_status=2, si_utime=0, si_stime=0} --- [pid 39332] +++ exited with 2 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=39332, si_status=2, si_utime=0, si_stime=0} ---
</pre>

**Comment by nunofonseca** [comment]
Hi,
Thank you for the update. I think that you may change the path using the environment variable TMPDIR (although I did not test it). 
Cheers

**Comment by nunofonseca** [comment]
Hi, I'm closing this issue since it seems that it is solved. Please reopen if that is not the case.
Cheers.
