### ISSUE TITLE
Strandedness setting in iRAP conf

### ISSUE THREAD

**Issue by freekvh** [nunofonseca/irap#29]
Hi Nuno,

I was wondering, this section refers directly t htseq-count, right?

    # strand specific protocol?
    #mylib1_strand=first 
    #mylib1_strand=second
    # Default value is both (strands)
    #mylib1_strand=both

But htseq-count only accepts --stranded=<yes/no/reverse>, and indeed I see that iRAP actually defaults to --stranded=no. Can I simply enter "reverse" as the setting (mylib1_strand=reverse) and will htseq-count then use that? Or should it be "second" for "reverse" and "first" for "stranded" and "both" for "no"?

Highest regards,

Freek.

**Comment by freekvh** [comment]
Hi Nuno,

Please ignore my question, we just found out that indeed htseq-count uses "reverse" when we select "first" in the iRAP config file.

Highest regards,

Freek.

**Comment by nunofonseca** [comment]
Hi Freek, Given that you already answered your question I'm closing this issue. Thanks.
