### ISSUE TITLE
Could pre-compiled binaries by considered as part of an installation method ?

### ISSUE THREAD

**Issue by PeteClapham** [nunofonseca/irap#30]
The current installation runs fine and to completion on Centos 7, although Ubuntu Xenial has been problematic. I wonder if it would help if the installation could take advantage of system provided or pre-compiled binaries.

This would greatly reduce the installation time (potentially > 3 hours) and potentially provide a known status outcome on a given platform ?

Thank you for irap
Pete

**Comment by nunofonseca** [comment]
Hi Pete, 
Thank your for your question.
Yes, ideally it would be better to take advantage of system provided or pre-compiled binaries. However, this approach raises several issues. First,  the binaries installed would need to match the versions integrated in iRAP - using a different version may have some nasty consequences, being the failure of the pipeline the less problematic. Also, there are too many linux flavours which complicates everything.  Another issue is that it requires root access to a machine, which not all users have. Lastly, it would involve too much time to maintain with a relative small return - iRAP is probably only installed no more than a couple of times a year by a user.

Note that if you are able to install the binaries (same version as installed by the iRAP install script) then you can skip the compilation of some libraries and reduce the installation time. To have finer control of what is installed you can use the "manual" installation [this page](https://github.com/nunofonseca/irap/wiki/2---How-to-install-and-update-iRAP#manual-install--option-2). 

Thanks and cheers.

**Comment by PeteClapham** [comment]
Hi, 

ty for the update, this all makes sense
Pete

**Comment by freekvh** [comment]
Snaps can solve both problems: https://snapcraft.io/
Of course making them requires some work :)

**Comment by nunofonseca** [comment]
Currently iRAP is available in docker images which kinda works around some of the issues of portability between Linux flavors and versions. Snapcraft looks interesting - it surely deserves some consideration.  Feel free to open an issue requesting this enhancement ;-)
