### ISSUE TITLE
missing file on R component

### ISSUE THREAD

**Issue by PeteClapham** [nunofonseca/irap#32]
Hi,
I apologize if I'm missing something or being particularly naive. I wonder if someone could post in the right direction with the following exit fail. The attached output is from script and with debug set. 

Thank you in advance
[irap.txt](https://github.com/nunofonseca/irap/files/1275152/irap.txt)

Pete

**Comment by nunofonseca** [comment]
Hi Pete,

I looked at  the irap.txt file and is a bit difficult to understand the first lines, namely the line one where irap env. variables are defined by running "source irap_setup.sh".  Did you run this command once before running irap?

Cheers.

**Comment by nunofonseca** [comment]
Hi again,
Looking more carefully at the log file I noticed that there was an I/O problem upstream.

'...
Loading gtf file /opt/irap_install/data/reference/homo_sapiens/ensembl.gtf
grep: write error'

Maybe the storage full?

Cheers.

**Comment by PeteClapham** [comment]
Hello,

Thank you for replying. We have over 100TB storage available in the top level dir and permissions all seem ok. I can manually create the file and potentially fix it as a fudge but it seems a little racey
Pete

**Comment by nunofonseca** [comment]
Hi,
There should not be necessary to create any file manually - that would void the purpose of having a pipeline ;-) 
The problem should be on the temporary folder (usually /tmp or other tmpfs folder setup on your computer node) used while uncompressing the input file and not on the toplevel folder.   The function that loads the data determines the temporary folder to use  by checking the environment variables TMPDIR, TMP and TEMP in turn and the first found which points to a writable directory is used: if none succeeds /tmp is used.   Does this make sense?

Cheers.

**Comment by freekvh** [comment]
This could be the same issue as I had, where /dev/shm (a ramdisk) is to small to hold the gtf file (my gtf file was 1.3 gb. In my case I increased /dev/shm from 1 to 4 GB and solved it. What size is your /dev/shm? (Output of: mount | grep /dev/shm)
