### ISSUE TITLE
Why the "samtools view -F 4" and the split of tsv files

### ISSUE THREAD

**Issue by freekvh** [nunofonseca/irap#34]
Hi Nuno,

As always I am thoroughly enjoying iRAP. I do wonder about two things though, these two things are hardcoded and I would prefer not to change "Nuno approved" settings because inevitably they lead to surprises down the road.

The first is: As an input for htseq-count, "samtools view -F 4 somebam.bam" is used. This removes the unmapped reads as input for htseq-count and sets them to 0. This means they are also disregarded in our QC reporting (using MultiQC), is there a reason for doing this?

The second: You/iRAP splits the output of htseq-count into the quantified genes and the "stats" (__no_feature, __ambiguous, etc). Again this confuses our QC reporting. This is not really a big deal because we can easily cat them together but still, I was wondering if there as a good reason for this (maybe because of subsequent normalization?)...

Highest regards,

Freek.

**Comment by nunofonseca** [comment]
Hi,
yes, usually there is a more or less good reason ;-) The removal of unmapped reads is motivated by reducing failures while running htseq and to try to speedup (slightly) the processing time. In the folder where the BAMs are generated you will find several files with statistics (including the number of unmapped reads). In the upcoming release of iRAP you should get a single file per run/library with  stats collected from QC, mapping and quantification.

The reason to remove the "stats" from the expression matrices is to ensure that the expression matrices only contain expression values and have the same format whatever the quantification method used (htseq, rsem, cufflinks, etc).  Makes sense?

Cheers.

**Comment by freekvh** [comment]
Hi Nuno,

Yes it makes sense, as expected ;)

For QC we, at the moment use MultiQC, it's beautiful looking QC program that can take input from many mappers and quantifiers (by default it requires their standard output though). Together with RSeQC it can provide a nice comprehensive overview of an experiment. But perhaps this is a bit out of scope for iRAP.

In any case, thank you for explaining (and for iRAP of course).

Freek.
