### ISSUE TITLE
how to norm the multiple bio replication TPM values into one tissue/condition value?

### ISSUE THREAD

**Issue by wangyugui** [nunofonseca/irap#37]
Hi.

how to norm the multiple bio replication TPM values into one tissue/condition value?

irap_single_lib is very good to process one sample(replication).

and is there a tool to norm multiple result into one value?

irap_deseq_norm seems to norm them to multiple value.

Best Regards

**Comment by wangyugui** [comment]
In the result of https://www.ebi.ac.uk/gxa/experiments/E-MTAB-5214/Downloads

It is a tissue(multiple sample) TPM/FPKM value.
How to get it from multiple irap_single_lib result ?

**Comment by nunofonseca** [comment]
Hi! The aggregated files available at https://www.ebi.ac.uk/gxa/experiments/E-MTAB-5214/Downloads are not generated by iRAP. You may want to send an email to arrayexpress-atlas@ebi.ac.uk requesting details on how those files are generated?
Cheers.
