### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by jodyphelan** [nunofonseca/irap#40]
Hi ,

I am getting an error: 
make: *** No rule to make target 'test/data/midge.gtf.mapTrans2Gene.tsv', needed by 'test/star/htseq2//KC0_A_AGTCAA_L005.se.transcripts.riu.htseq2.irap.tsv'. Stop.

Not sure what exactly went wrong... doesn't seem like there are any other errors before this.

Any thoughts on what the problem might be?

Thanks,
Jody

**Comment by nunofonseca** [comment]
Hi Jody,
Thank you for reporting the issue. 
Are you using the latest version of iRAP (v0.8.5.p8)?
If so, it would be easier to pinpoint the problem if you could  run irap again and provide all the messages printed  to the terminal? iRAP should quickly fail again in the same place.
Thanks.

**Comment by jodyphelan** [comment]
Hi Nuno,

Appologies - I have recreated the configuration file and now it seems to work.

Jody

**Comment by nunofonseca** [comment]
Great! Please reopen the issue if the problem returns. 
Cheers.
