### ISSUE TITLE
bamToFastq pickup the wrong bam file name

### ISSUE THREAD

**Issue by byb121** [nunofonseca/irap#41]
When input is a bam file (eg: `the_sample.bam`), bamToFastq is using `the_sample.bam.sorted.bam` as its input, while samtools sort produces a `the_sample.bam.sorted`, hence bamToFastq produces empty Fastqs.

bamToFastq should raise an error at this point as well, not to wait till Fastqc complains.

**Comment by byb121** [comment]
seems just need to change `sorted.bam` to `sorted` on this line:
https://github.com/nunofonseca/irap/blob/master/scripts/irap_fastq_qc#L359

**Comment by nunofonseca** [comment]
It should be fixed in the new version of the script (devel branch). The code now uses samtools to perform the conversion. Please reopen the issue if the problem persists. Cheers.
