### ISSUE TITLE
-R is ignored when R is not preinstalled

### ISSUE THREAD

**Issue by byb121** [nunofonseca/irap#42]
https://github.com/nunofonseca/irap/blob/master/scripts/irap_install.sh#L134-L139
Those lines mean if R is not preinstalled, even `-R` is issued, iRAP installation will be stopped.

**Comment by nunofonseca** [comment]
Thank you for reporting the issue. The irap_install.sh (in devel) should keep going if R is not available and -R is provided.
Cheers.
