### ISSUE TITLE
bamToFastq produces overwhelming warnings due to secondary alignments

### ISSUE THREAD

**Issue by byb121** [nunofonseca/irap#45]
warnings like below:
```
*****WARNING: Query HF2_23587:5:2218:9293:30855 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query HF2_23587:5:2218:9577:35567 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query HF2_23587:5:2218:9871:3196 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
*****WARNING: Query HF2_23587:5:2218:9881:40420 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
```
I checked a few, all have secondary alignments in the input BAM. 

This won't be an issue if input BAM is unaligned, but ours happen to be aligned and have secondary alignments.

**Comment by nunofonseca** [comment]
Hi again! Indeed there was an implicit assumption that the input BAMs were uBAM (only contained unaligned reads). The conversion of BAM to fastq is now  (devel version) made  with samtools and the warnings should disappear. Please reopen the issue after the new release if the issue persists.
Cheers.
