### ISSUE TITLE
compress FastQ?

### ISSUE THREAD

**Issue by byb121** [nunofonseca/irap#46]
My inputs are BAMs. With "base quality filtering" turned on, iRAP generates 10 FastQ files per BAM (2 are along with the input BAM, 8 are in output/data folder). They are not compressed and take quite a lot of disk spaces (input BAM is 4GB, the total size of FastQs is about 70GB). If they are compressed while writing, we can run more samples simultaneously.

**Comment by nunofonseca** [comment]
Hi! That is a good point. That has been addressed in the new upcoming version of iRAP - the fastq files are always compressed and it should generate a few less temporary fastq files.
