### ISSUE TITLE
contamination genomes built with bowtie2 won't be recognised in contamination filtering

### ISSUE THREAD

**Issue by byb121** [nunofonseca/irap#47]
iRAP by default uses bowtie to check contaminations from other genomes in raw reads,  so following the example below, genomes built won't be taken by iRAP.
https://github.com/nunofonseca/irap/blob/master/examples/ex_add2contaminationDB2.sh#L5

**Comment by nunofonseca** [comment]
Hi!  If you include
cont_mapper=bowtie2
then bowtie2 indices will be used by iRAP instead of bowtie1. In the upcoming new release, bowtie2 will be used by default. Please reopen the ticket if I misunderstood the question. Cheers.
