### ISSUE TITLE
Not handling 'qual_filtering=none' as expected

### ISSUE THREAD

**Issue by byb121** [nunofonseca/irap#48]
When  'qual_filtering=none' is specified and input is not a un-compressed FastQ (e.g. a BAM or fastq.gz), iRAP creates a symbolic link to the input only without checking if it's in the right format for the downstream mapper to use.

**Comment by nunofonseca** [comment]
Again, thank you for the feedback. The issue that you pointed out (fastq.gz and BAM as input combined with qual_filtering=none) should have been  fixed in the devel branch. Cheers.
