### ISSUE TITLE
failed to load GTF file

### ISSUE THREAD

**Issue by byb121** [nunofonseca/irap#53]
Because of this issue: https://github.com/Rdatatable/data.table/issues/2272

https://github.com/nunofonseca/irap/blob/master/aux/R/irap_utils.R#L1461 will throw an error for large GTF files while running within a Docker container, which has only 64M for /dev/shm by default for "fread" to use to load GTF.

iRAP should probably use the latest version of data.table, which has the fix.

**Comment by nunofonseca** [comment]
Hi,
Which version of iRAP are you using?
Cheers.

**Comment by byb121** [comment]
I was on v0.8.5.p8, didn't see the new release. Will have a go later this week.

**Comment by nunofonseca** [comment]
Great, please let me know if you encounter any issues. Cheers.
