### ISSUE TITLE
TPM values rounded to 2 decimals

### ISSUE THREAD

**Issue by freekvh** [nunofonseca/irap#55]
Hi Nuno,

I was wondering, is there any reason why TPM values are rounded to 2 decimals? In some experiments I see over 20% of genes <= 0.01, I feel that I'm losing information, at least when the sequencing depth is sufficient. What do you think?

I'm using star-rsem (iRAP 0.8.5p2) by the way.

Best regards,

Freek.

**Comment by nunofonseca** [comment]
Hi Freek,
Normalized expressions values generated by iRAP (irap_raw2metric script) are rounded to 2 decimal places before saving to the file. In many papers and portals TPMs are provided up to 1 decimal place (e.g., GTex portal). Anyway, I added --round option to  irap_raw2metric which will allow you to define the number of decimal places.
Cheers.

**Comment by freekvh** [comment]
Great, thank you! So, for thoroughness, could this be added to the conf file like this (where X is an int)?

```
##################################################################
# Overriding/changing the parameters of the quantification methods:
# _params=options
# Example
# htseq_params= -q
irap_raw2metric=--round X
```

**Comment by nunofonseca** [comment]
Yes, it is now added (but still on the devel branch). Please reopen this issue if necessary.
Cheers.
