### ISSUE TITLE
Error running Docker image

### ISSUE THREAD

**Issue by larsgtoicr** [nunofonseca/irap#60]
Running Quick Example started tutorial. https://github.com/nunofonseca/irap/wiki/7-Quick-Example

Get the following error:
*****************************************************
* IRAP 0.8.5d3
* Developed by Nuno Fonseca (authorname (at) acm.org)
* This pipeline is distributed  under the terms of the GNU General Public License 3
*
* Initializing...
* Trying to load configuration file ecoli_example.conf...
* Configuration loaded.
*
* Required Parameters:
*       name=ecoli_ex
*       data_dir=/opt/irap/data
*       species=ecoli_k12
*       raw_data_dir=/opt/irap/data/raw_data/ecoli_k12/
*       reference=Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.dna.chromosome.I.fa.gz
*       gtf_file  = Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.gtf
*       Transcripts = /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa
*       gff3_file  = ecoli_ex/data/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.gff3
* Validating se and pe
*       se=FA FB FC FD FE
*       contrasts=GAvsGB GBvsGA
*      GAvsGB=GA GB
*       GA=FA FB FC
*       GB=FD FE
*      GBvsGA=GB GA
*       GB=FD FE
*       GA=FA FB FC
*       groups=  parameter not defined, this should be defined if you intend to generate an HTML report for the inferred gene/level/transcript quantification
*       technical.replicates=NONE
*
* Optional Parameters:
*       rnaseq_type=blk
*       max_threads=8
*       tmp_dir=/opt/irap/data/tmp (temporary directory)
*       qc/filter=on
*       mapper=hisat2
*       quant_method=htseq2
*       exon_quant=n
*       transcript_quant=n
*       transcript_expr=n
*       quant_norm_tool=none
*       quant_norm_method=none
*       mapper_splicing=yes
*       de_method=deseq
*       de_pvalue_cutoff=0.05
*       transcript_de_method=none
*       transcript_de_pvalue_cutoff=0.05
*       exon_de_method=none
*       exon_de_pvalue_cutoff=0.05
bash: bc: command not found
*       barcode_post_process_bam=n
* WARNING: HISAT2 support is still under development
*       gse_tool=none
% YAP execution halted
*========================================================
* Files/folders:
** Top level folder: ecoli_ex
** Aux data: ecoli_ex/data
** QC for input files: ecoli_ex/irap_qc
** Alignment files: ecoli_ex/irap_qc/hisat2
** Quantification matrices: ecoli_ex/irap_qc/hisat2/htseq2
** Gene level DE: ecoli_ex/irap_qc/hisat2/htseq2/deseq
--------------------------------------------------------
* 30/05/2018 20:24:42 : [DONE] Initialization
* 30/05/2018 20:24:42 : [DONE] Directory structure created
irap_gtf_to_fasta -g /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.gtf --genome /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.dna.chromosome.I.fa --types 'protein_coding|IG_([a-zA-Z0-9]+)_gene|TR_([a-zA-Z0-9]+)_gene' --out /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp && mv /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa
gtf=/opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.gtf
fasta=/opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.dna.chromosome.I.fa
types=protein_coding|IG_([a-zA-Z0-9]+)_gene|TR_([a-zA-Z0-9]+)_gene
out=/opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp
Creating temporary gtf...
Creating temporary gtf...done.
Loading temporary GTF...
Transcripts loaded:4003
done.
Creating fasta (1/2)...
sh: 1: set: Illegal option -o pipefail
set -o pipefail; tophat2_gtf_to_fasta /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp.tmp.gtf /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.dna.chromosome.I.fa /dev/stdout|tail -n +2| sed -E  's/^>([a-zA-Z0-9|]+)\s/>/;s/\s.*//' > /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp.tmp1 failed: 512make: *** [/opt/irap/scripts/../aux/mk/irap_core.mk:1938: /opt/irap/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa] Error 1

**Comment by nunofonseca** [comment]
Thank you for the bug report. I just pushed a commit to the devel branch that should fix the problem with irapBAM2stats  - sh is being used instead of bash. You may find a docker file for the devel branch in docker/Dockerfile-devel (the image should  be available soon in docker hub - https://hub.docker.com/r/nunofonseca/irap/ ).
Cheers.

**Comment by nunofonseca** [comment]
Hi,
This should be solved in the latest release. The docker images for different linux flavours are available in github. Please reopen the issue if the problem persists.
Cheers.
